//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Drawchad {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Drawchad() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrawchadDomain.Resources.Drawchad", typeof(Drawchad).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed. Incorrect Email or Password..
        /// </summary>
        public static string DRAWCHAD_AUTHORIZED_FAILED {
            get {
                return ResourceManager.GetString("DRAWCHAD_AUTHORIZED_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This course is already existed in your cart..
        /// </summary>
        public static string DRAWCHAD_COURSE_ALREADY_ADDED {
            get {
                return ResourceManager.GetString("DRAWCHAD_COURSE_ALREADY_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course level is invalid..
        /// </summary>
        public static string DRAWCHAD_COURSE_LEVEL_INVALID_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_COURSE_LEVEL_INVALID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course material is invalid..
        /// </summary>
        public static string DRAWCHAD_COURSE_MATERIAL_INVALID_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_COURSE_MATERIAL_INVALID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course price must greater than 0..
        /// </summary>
        public static string DRAWCHAD_COURSE_PRICE_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_COURSE_PRICE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty..
        /// </summary>
        public static string DRAWCHAD_EMAIL_EMPTY_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_EMAIL_EMPTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid format..
        /// </summary>
        public static string DRAWCHAD_EMAIL_INVALID_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_EMAIL_INVALID_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam result must between {0} and {1}..
        /// </summary>
        public static string DRAWCHAD_EXAM_RESULT_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_EXAM_RESULT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson is invalid for submit exam..
        /// </summary>
        public static string DRAWCHAD_EXAM_SUBMIT_INVALID_LESSON {
            get {
                return ResourceManager.GetString("DRAWCHAD_EXAM_SUBMIT_INVALID_LESSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image url is invalid..
        /// </summary>
        public static string DRAWCHAD_IMAGE_URL_FORMAT_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_IMAGE_URL_FORMAT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID.
        /// </summary>
        public static string DRAWCHAD_INVALID_ID {
            get {
                return ResourceManager.GetString("DRAWCHAD_INVALID_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum valid value of the page index is 0..
        /// </summary>
        public static string DRAWCHAD_PAGE_INDEX_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_PAGE_INDEX_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum valid value of the page size is 1..
        /// </summary>
        public static string DRAWCHAD_PAGE_SIZE_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_PAGE_SIZE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password length must between {0} and {1}..
        /// </summary>
        public static string DRAWCHAD_PASSWORD_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_PASSWORD_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone is invalid..
        /// </summary>
        public static string DRAWCHAD_PHONE_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_PHONE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed. System error..
        /// </summary>
        public static string DRAWCHAD_SERVER_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("DRAWCHAD_SERVER_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length must between {0} and {1}..
        /// </summary>
        public static string DRAWCHAD_SIGNUP_NAME_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("DRAWCHAD_SIGNUP_NAME_LENGTH_ERROR", resourceCulture);
            }
        }
    }
}
